// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzv5T93ieTfxzD8y-RMdCMgicSfVGIsMk',
    appId: '1:34200266054:web:751a4715e9a6a6cef77147',
    messagingSenderId: '34200266054',
    projectId: 'fluttersignin-30b78',
    authDomain: 'fluttersignin-30b78.firebaseapp.com',
    storageBucket: 'fluttersignin-30b78.appspot.com',
    measurementId: 'G-CB67FZDW9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD5G5kbVWLzYOft79N1jy9uRPmoKsC7VY',
    appId: '1:34200266054:android:37f0f18e9b469eb2f77147',
    messagingSenderId: '34200266054',
    projectId: 'fluttersignin-30b78',
    storageBucket: 'fluttersignin-30b78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4k-z7A0KV1bijQ9LvZgoSjQSRdSnZ568',
    appId: '1:34200266054:ios:4bde8628f2185becf77147',
    messagingSenderId: '34200266054',
    projectId: 'fluttersignin-30b78',
    storageBucket: 'fluttersignin-30b78.appspot.com',
    iosClientId: '34200266054-9k8qr1bsoankjfplrovtsoeaivoj5uj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.truth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzv5T93ieTfxzD8y-RMdCMgicSfVGIsMk',
    appId: '1:34200266054:web:d57c0d7706af230ff77147',
    messagingSenderId: '34200266054',
    projectId: 'fluttersignin-30b78',
    authDomain: 'fluttersignin-30b78.firebaseapp.com',
    storageBucket: 'fluttersignin-30b78.appspot.com',
    measurementId: 'G-MJ0E9NBSQD',
  );

}